### ISSUE TITLE
nipype needs to be 0.12

### ISSUE THREAD

**Issue by florisvanvugt** [FCP-INDI/C-PAC#668]
When running the test pipeline, I kept getting an error
```
'module' object has no attribute 'Refit'
an exception occurred
```

This turned out to be due, I believe, to my nipype being too recent. 
By default the installation gives you the latest nipype (currently 0.13) but you actually need 0.12. It was solved by downloading 0.12 from the nipype repository (https://github.com/nipy/nipype/tags) and then running something like:

```
pip install ~/Downloads/nipype-0.12.1.tar.gz
```

**Comment by sgiavasis** [comment]
Hi floris,

Yes- CPAC is only compatible with Nipype versions up to 0.12.x. We are in the process of updating our interface calls to work with 0.13+. I apologize that our documentation hasn't been updated to explicitly mention that 0.12 is also a maximum.

**Comment by florisvanvugt** [comment]
Yes, that would be useful. Also just for the record (you were probably aware of this already), this would have to be updated in the automated installation script for Ubuntu. Currently when you install CPAC using that script, it will fail because it installs the latest nipype and not 0.12. Thanks.
